### ISSUE TITLE
Improving Variables' names!

### ISSUE THREAD

**Issue by AliNajafi1998** [MR-AliHaashemi/Python-Discord-RPC#1]
https://github.com/MR-AliHaashemi/Python-Discord-RPC/blob/32c41bee8c562a40b70763f89798230c716feb28/RichPresence.py#L33

if it is the user state then name the variable ```user_state``` and remove the comment!

***This was just an example try to choose presentative names for your variables and remove redundant comments!***

**Comment by MR-AliHaashemi** [comment]
I can't do it with my local knowledge of python for now, because it's pypresence's module variable and editing that... I don't think be is easy.

But, yeah, I need to change lots of things in the variables like changing "str" to an example instead of the type the needed type in string LOL.

Thanks for opening this issue, I'll work on it.
